name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    if: github.repository == 'gen740/cppygen'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup pip
      run: |
        pip install -U pip

    - name: Install llvm-15 and llvm-16
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16 all

    - name: Install
      run: |
        pip install .

    - name: Tests (llvm-15)
      run: |
        pytest
      env:
        CPPYGEN_LIBCLANG_PATH: /usr/lib/llvm-15/lib/libclang.so

    - name: Tests (llvm-16)
      run: |
        pytest
      env:
        CPPYGEN_LIBCLANG_PATH: /usr/lib/llvm-16/lib/libclang.so
